channels:
  - bioconda
  - r
  - conda-forge
  - bushmanlab
  - defaults
dependencies:
  - snakemake
  - blat
  - bwa
  - samtools
  - graphviz
  - pandoc
  - semantic_version
  - ruamel.yaml
  - r=3.5.1
  - r-base
  - r-argparse
  - r-pander
  - r-kableextra
  - r-yaml
  - r-tidyverse
  - r-magrittr
  - r-ggforce
  - r-data.table
  - r-matrix
  - r-igraph
  - r-rmarkdown
  - r-knitr
  - r-scales
  - r-rcolorbrewer
  - r-digest
  - r-statmod
  - r-devtools
  - r-testthat
  - r-roxygen2
  - bioconductor-biocgenerics
  - bioconductor-iranges
  - bioconductor-genomicranges
  - bioconductor-hiannotator
  - bioconductor-biostrings
  - bioconductor-shortread
  - bioconductor-rsamtools
  - bioconductor-bsgenome
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
